/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/earth.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Earth = (props) => {
  const { nodes, materials } = useGLTF('/modelsearth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.object_0.geometry} material={materials.object_0} />
      <mesh geometry={nodes.object_1.geometry} material={materials.object_1} />
      <mesh geometry={nodes.object_2.geometry} material={materials.object_2} />
      <mesh geometry={nodes.object_3.geometry} material={materials.object_3} />
      <mesh geometry={nodes.object_4.geometry} material={materials.object_4} />
      <mesh geometry={nodes.object_5.geometry} material={materials.object_5} />
      <mesh geometry={nodes.object_6.geometry} material={materials.object_6} />
      <mesh geometry={nodes.object_7.geometry} material={materials.object_7} />
      <mesh geometry={nodes.object_8.geometry} material={materials.object_8} />
      <mesh geometry={nodes.object_9.geometry} material={materials.object_9} />
      <mesh geometry={nodes.object_10.geometry} material={materials.object_10} />
      <mesh geometry={nodes.object_11.geometry} material={materials.object_11} />
    </group>
  )
}

useGLTF.preload('/models/earth.glb')

export default Earth
