/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/earth.glb 
Author: camelCaseSensitive (https://sketchfab.com/camelCaseSensitive)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-earth-5f6ea1111fda4cf6a7b36cf4ce200d1b
Title: Lowpoly Earth
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Earth = (props) => {
  const { nodes, materials } = useGLTF('/models/earth.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/earth.glb')

export default Earth
