/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/rubiks_cube.glb 
Author: Voldepreuss (https://sketchfab.com/Voldepreuss)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubiks-cube-3b74eeb531ca4f49a0274e2887526aee
Title: Rubiks Cube
*/

import React from 'react'
import {Float, useGLTF} from '@react-three/drei'
import gsap from "gsap";
import {useGSAP} from "@gsap/react";

const RubiksCube = (props) => {
  const { nodes, materials } = useGLTF('/models/rubiks_cube.glb')

  const cubeRef = React.useRef()

  // Do rotations in infinity
  useGSAP(() => {
    gsap.to(
      cubeRef.current.rotation,
      {
        x: 2 * Math.PI - Math.PI / 2,
        y: 2 * Math.PI,
        duration: 5,
        ease: 'none',
        repeat: -1
      }
    )
  }, [cubeRef])

  return (
    <Float floatIntensity={3}>
      <group ref={cubeRef} {...props} rotation={[-Math.PI / 2, 0, 0]} scale={0.8} dispose={null}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks_1.geometry} material={materials.Blue} />
          <mesh geometry={nodes.Rubiks_2.geometry} material={materials.Yellow} />
          <mesh geometry={nodes.Rubiks_3.geometry} material={materials.Orange} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks011_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks011_1.geometry} material={materials.White} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks012_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks012_1.geometry} material={materials.Green} />
          <mesh geometry={nodes.Rubiks012_2.geometry} material={materials.White} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks013_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks013_1.geometry} material={materials.White} />
          <mesh geometry={nodes.Rubiks013_2.geometry} material={materials.Blue} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks014_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks014_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Rubiks014_2.geometry} material={materials.White} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks015_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks015_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Rubiks015_2.geometry} material={materials.Green} />
          <mesh geometry={nodes.Rubiks015_3.geometry} material={materials.White} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks017_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks017_1.geometry} material={materials.White} />
          <mesh geometry={nodes.Rubiks017_2.geometry} material={materials.Yellow} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks018_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks018_1.geometry} material={materials.Green} />
          <mesh geometry={nodes.Rubiks018_2.geometry} material={materials.White} />
          <mesh geometry={nodes.Rubiks018_3.geometry} material={materials.Yellow} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks019_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks019_1.geometry} material={materials.White} />
          <mesh geometry={nodes.Rubiks019_2.geometry} material={materials.Blue} />
          <mesh geometry={nodes.Rubiks019_3.geometry} material={materials.Yellow} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks027_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks027_1.geometry} material={materials.Green} />
          <mesh geometry={nodes.Rubiks027_2.geometry} material={materials.Yellow} />
          <mesh geometry={nodes.Rubiks027_3.geometry} material={materials.Orange} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks028_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks028_1.geometry} material={materials.Yellow} />
          <mesh geometry={nodes.Rubiks028_2.geometry} material={materials.Orange} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks029_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks029_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Rubiks029_2.geometry} material={materials.Blue} />
          <mesh geometry={nodes.Rubiks029_3.geometry} material={materials.Orange} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks030_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks030_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Rubiks030_2.geometry} material={materials.Green} />
          <mesh geometry={nodes.Rubiks030_3.geometry} material={materials.Orange} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks031_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks031_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Rubiks031_2.geometry} material={materials.Orange} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks032_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks032_1.geometry} material={materials.Blue} />
          <mesh geometry={nodes.Rubiks032_2.geometry} material={materials.Orange} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks033_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks033_1.geometry} material={materials.Green} />
          <mesh geometry={nodes.Rubiks033_2.geometry} material={materials.Orange} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks034_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks034_1.geometry} material={materials.Orange} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks038_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks038_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Rubiks038_2.geometry} material={materials.White} />
          <mesh geometry={nodes.Rubiks038_3.geometry} material={materials.Blue} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks044_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks044_1.geometry} material={materials.Blue} />
          <mesh geometry={nodes.Rubiks044_2.geometry} material={materials.Yellow} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks045_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks045_1.geometry} material={materials.Green} />
          <mesh geometry={nodes.Rubiks045_2.geometry} material={materials.Yellow} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks046_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks046_1.geometry} material={materials.Yellow} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks047_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks047_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Rubiks047_2.geometry} material={materials.Blue} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks048_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks048_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Rubiks048_2.geometry} material={materials.Green} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks049_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks049_1.geometry} material={materials.material} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks050_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks050_1.geometry} material={materials.Blue} />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rubiks051_0.geometry} material={materials.Bevel} />
          <mesh geometry={nodes.Rubiks051_1.geometry} material={materials.Green} />
        </group>
        <mesh geometry={nodes.Rubiks052_0.geometry} material={materials.Bevel} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/rubiks_cube.glb')

export default RubiksCube
